Merge 2.6.7 release to master
OpenVPN/openvpn-build pull request #516
Opened 2023-11-09 12:05 UTC by uddr

2023-11-09 17:44 UTC, flichtenheld commented on src/openvpn
This is wrong. Merge from release/2.6 to master shouldn't change content of openvpn submodule

2023-11-09 17:44 UTC, flichtenheld requested changes
Wrong conflict resolution in src/openvpn

2023-11-10 15:32 UTC, uddr commented on src/openvpn
thanks, updated

2023-11-10 17:41 UTC, flichtenheld approved these changes

2023-11-14 13:35 UTC, merged